import Head from 'next/head'
import { Fragment, useState, useEffect } from 'react'
import { SearchIcon } from '@heroicons/react/outline'
import CountryList from '../components/CountryList';
import Loader from "../components/Loader"

export default function Home() {
  const [region, setRegion] = useState('');
  const [list, setList] = useState([]);
  const [allList, setAllList] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [searchText, setSearchText] = useState('');

  const fetchAll = async () => {
    setIsLoading(true);
    const res = await fetch('https://restcountries.com/v3.1/all');
    const data = await res.json();
    setAllList(data);
    setList(data);
    setIsLoading(false);
  }

  useEffect(() => { fetchAll() }, [])

  const changeRegionHandler = async (e) => {
    setIsLoading(true)
    setRegion(e.target.value)
    if (e.target.value === "") {
      setList(allList)
    } else {
      const res  = await fetch(`https://restcountries.com/v3.1/region/${e.target.value}`);
      const data = await res.json();
      setList(data);
    }
    setIsLoading(false)
  }

  const handleSearch = e => {
    setSearchText(e.target.value);
    const filteredCountry = allList.filter(country => country.name.common.toLowerCase().includes(e.target.value.toLowerCase()));
    setList(filteredCountry)
  }

  if (isLoading) return <Loader />

  return (
    <Fragment>
      <Head>
        <title>Rest Country API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Link href="/test">Go To Test Page</Link> */}
      <div className="md:flex items-center justify-between">
        <div className="shadow-md py-2 px-4 w-72 flex items-center rounded-md">
          <SearchIcon className="h-5 mr-3" />
          <input 
            value={searchText}
            onChange={handleSearch}
            type="search"
            placeholder="search for a country..."
            className='w-full bg-transparent placeholder:font-semibold outline-none'
          />
        </div>

        <select
          value={region}
          onChange={changeRegionHandler}
          className='mt-6 md:mt-0 shadow-md py-2 px-4 max-w-2xl bg-transparent placeholder:font-semibold outline-none'
        >
          <option value="" className='bg-white dark:bg-gray-700'>Filter by reigon</option>
          <option className='bg-white dark:bg-gray-700' value="africa">Africa</option>
          <option className='bg-white dark:bg-gray-700' value="america">America</option>
          <option className='bg-white dark:bg-gray-700' value="asia">Asia</option>
          <option className='bg-white dark:bg-gray-700' value="europe">Europe</option>
          <option className='bg-white dark:bg-gray-700' value="oceania">Oceania</option>
        </select>
      </div>

      <CountryList data={list} />
    </Fragment>
  )
}
